module(load="imudp")
module(load="omfwd")

input(type="imudp" port="514")

$template MikroTikLogs,"/logs/mikrotik/%fromhost-ip%/%$YEAR%-%$MONTH%-%$DAY%.log"

# запись логов
action(
  type="omfile"
  dynaFile="MikroTikLogs"
  createDirs="on"
)

# forward parser
*.* action(
  type="omfwd"
  target="mikrotik_parser"
  port="1514"
  protocol="tcp"
  template="RSYSLOG_TraditionalForwardFormat"
)
